name: Release
on:
  pull_request:
    types: [closed]

permissions:
  contents: write # Create releases

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.merged == true && 
      contains(github.event.pull_request.title, 'Post-Release')
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        
      - name: Extract version and create tag
        id: tag-version
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          VERSION=$(echo "$PR_TITLE" | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git tag $VERSION
          git push origin $VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag-version.outputs.version }}
          release_name: ${{ steps.tag-version.outputs.version }}
          body: |
            AWS EFS CSI Driver

            ## CHANGELOG
            See [CHANGELOG](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/CHANGELOG-2.x.md) for full list of changes
          draft: false
          prerelease: false
